version: '3.8'

services:
  supervisor-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
      - "9001:9001"
    environment:
      - ILLA_SERVER_HOST=0.0.0.0
      - ILLA_SERVER_PORT=8003
      - ILLA_SERVER_INTERNAL_PORT=9001
      - ILLA_SERVER_MODE=release
      - ILLA_DEPLOY_MODE=self-host
      - ILLA_SECRET_KEY=your_secret_key_here
      - ILLA_SUPERVISOR_PG_ADDR=postgres
      - ILLA_SUPERVISOR_PG_PORT=5432
      - ILLA_SUPERVISOR_PG_USER=illa_supervisor
      - ILLA_SUPERVISOR_PG_PASSWORD=illa2022
      - ILLA_SUPERVISOR_PG_DATABASE=illa_supervisor
      - ILLA_REDIS_ADDR=redis
      - ILLA_REDIS_PORT=6379
      - ILLA_REDIS_PASSWORD=
      - ILLA_REDIS_DATABASE=0
      - ILLA_DRIVE_TYPE=minio
      - ILLA_DRIVE_ACCESS_KEY_ID=minioadmin
      - ILLA_DRIVE_ACCESS_KEY_SECRET=minioadmin
      - ILLA_DRIVE_ENDPOINT=minio:9000
      - ILLA_DRIVE_SYSTEM_BUCKET_NAME=illa-supervisor
      - ILLA_DRIVE_TEAM_BUCKET_NAME=illa-supervisor-team
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=illa_supervisor
      - POSTGRES_PASSWORD=illa2022
      - POSTGRES_DB=illa_supervisor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data: 